### ISSUE TITLE
agent flow v1 failing after after upgrading to v3.0.3

### ISSUE THREAD

**Issue by sbaudet85** [FlowiseAI/Flowise#4756]
### Describe the bug

I upgraded my on-premise docker container to v3.0.3, and now, my existing agentflow v1 is raising an error when I send a question:

```
2025-06-30 08:14:26 [ERROR]: [server]: [b91a8199-b0b1-4e43-92aa-bc19e70c3c40]: Error: langChainTracer.convertToRunTree is not a function
Error: langChainTracer.convertToRunTree is not a function
    at buildAgentGraph (/usr/local/lib/node_modules/flowise/dist/utils/buildAgentGraph.js:347:19)
    at async executeFlow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:365:31)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:799:28)
    at async Object.buildChatflow (/usr/local/lib/node_modules/flowise/dist/services/predictions/index.js:9:28)
    at async createPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/predictions/index.js:72:41)
2025-06-30 08:14:26 [ERROR]: [server]: Error: Error buildAgentGraph - langChainTracer.convertToRunTree is not a function
Error: Error buildAgentGraph - langChainTracer.convertToRunTree is not a function
    at buildAgentGraph (/usr/local/lib/node_modules/flowise/dist/utils/buildAgentGraph.js:353:15)
    at async executeFlow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:365:31)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:799:28)
    at async Object.buildChatflow (/usr/local/lib/node_modules/flowise/dist/services/predictions/index.js:9:28)
    at async createPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/predictions/index.js:72:41)
```

I don't master agent flow v2 at the moment, and couldn't assess how to reproduce the multiagent flow with supervisor/workers. I'd like to just be able to upgrade without such failure until I have time to be able to rewrite it in v2 with the same level of quality. Thanks.

### To Reproduce

1. On Flowise AI 3.0.2, have an agentflow v1 with a supervisor and several workers
2. Upgrade to 3.0.3
3. Send a question and monitor the log

### Expected behavior

No error

### Use Method

Docker

### Flowise Version

3.0.2

### Operating System

Linux

### Browser

Edge

**Comment by walldemar** [comment]
got the same problem :(

**Comment by dentroai** [comment]
same here. Agents v1 aren't backwards compatible?

Thanks @sbaudet85 for mentioning you got the error after upgrading to v3.0.3. 
Could downgrade to v3.0.2 and my flow works again for the moment, thanks for saving me a lot of headache!

**Comment by HenryHengZJ** [comment]
Maybe we updated the core version, will take a look!

**Comment by sbaudet85** [comment]
I have deployed another instance of Flowise AI 3.0.4, and imported my agent flow v1.
I get an interesting warning:

Client version 1.13.0 is incompatible with server version 1.15.0. Major versions should match and minor version difference must not exceed 1. Set checkCompatibility=false to skip version check.

**Comment by HenryHengZJ** [comment]
tested and it works fine: 

<img width="1857" height="767" alt="Image" src="https://github.com/user-attachments/assets/04aade56-a606-4360-bbc8-5efcf0add3ab" />

**Comment by sbaudet85** [comment]
my flow was involving a supervisor and 4 workers, not a sequential flow. Please can you try maybe?

**Comment by takefy-dev** [comment]
Not working for me too

**Comment by takefy-dev** [comment]
Hey any news on this ? @HenryHengZJ

**Comment by HenryHengZJ** [comment]
can anyone export the flow for me to test it out?

**Comment by takefy-dev** [comment]
[bc chat Agents.json](https://github.com/user-attachments/files/21548241/bc.chat.Agents.json)

@HenryHengZJ

**Comment by Slagveer** [comment]
I've switched of the analyse tool (LangSmith). That solved the issue!

**Comment by takefy-dev** [comment]
Just tried that @Slagveer it does not solve it for me

**Comment by sbaudet85** [comment]
Disabling Langsmith didn't solve it. I still get on FlowiseAI 3.0.4:

2025-08-04 14:28:21 [VERBOSE]: [b91a8199-b0b1-4e43-92aa-bc19e70c3c40]: [chain/error] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda] [2ms] Chain run errored with error: "langChainTracer.convertToRunTree is not a function\n\nTypeError: langChainTracer.convertToRunTree is not a function\n    at AsyncLocalStorageProvider.runWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/singletons/index.cjs:37:39)\n    at /usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1529:64\n    at new Promise (<anonymous>)\n    at RunnableLambda._invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1524:16)\n    at RunnableLambda._callWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:223:34)\n    at async RunnableSequence.invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1155:33)\n    at async Promise.allSettled (index 0)\n    at async executeTasks (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:549:21)\n    at async CompiledStateGraph._transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:464:17)\n    at async CompiledStateGraph._transformStreamWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:308:30)\n    at async CompiledStateGraph.transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:529:26)\n    at async Object.pull (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/utils/stream.cjs:103:41)"
2025-08-04 14:28:21 [VERBOSE]: [b91a8199-b0b1-4e43-92aa-bc19e70c3c40]: [chain/error] [1:chain:LangGraph > 3:chain:supervisor] [5ms] Chain run errored with error: "langChainTracer.convertToRunTree is not a function\n\nTypeError: langChainTracer.convertToRunTree is not a function\n    at AsyncLocalStorageProvider.runWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/singletons/index.cjs:37:39)\n    at /usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1529:64\n    at new Promise (<anonymous>)\n    at RunnableLambda._invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1524:16)\n    at RunnableLambda._callWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:223:34)\n    at async RunnableSequence.invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1155:33)\n    at async Promise.allSettled (index 0)\n    at async executeTasks (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:549:21)\n    at async CompiledStateGraph._transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:464:17)\n    at async CompiledStateGraph._transformStreamWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:308:30)\n    at async CompiledStateGraph.transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:529:26)\n    at async Object.pull (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/utils/stream.cjs:103:41)"
2025-08-04 14:28:21 [VERBOSE]: [b91a8199-b0b1-4e43-92aa-bc19e70c3c40]: [chain/error] [1:chain:LangGraph] [38ms] Chain run errored with error: "langChainTracer.convertToRunTree is not a function\n\nTypeError: langChainTracer.convertToRunTree is not a function\n    at AsyncLocalStorageProvider.runWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/singletons/index.cjs:37:39)\n    at /usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1529:64\n    at new Promise (<anonymous>)\n    at RunnableLambda._invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1524:16)\n    at RunnableLambda._callWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:223:34)\n    at async RunnableSequence.invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:1155:33)\n    at async Promise.allSettled (index 0)\n    at async executeTasks (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:549:21)\n    at async CompiledStateGraph._transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:464:17)\n    at async CompiledStateGraph._transformStreamWithConfig (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/runnables/base.cjs:308:30)\n    at async CompiledStateGraph.transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/dist/pregel/index.cjs:529:26)\n    at async Object.pull (/usr/local/lib/node_modules/flowise/node_modules/@langchain/langgraph/node_modules/@langchain/core/dist/utils/stream.cjs:103:41)"
2025-08-04 14:28:21 [ERROR]: [server]: [b91a8199-b0b1-4e43-92aa-bc19e70c3c40]: Error: langChainTracer.convertToRunTree is not a function
Error: langChainTracer.convertToRunTree is not a function
    at buildAgentGraph (/usr/local/lib/node_modules/flowise/dist/utils/buildAgentGraph.js:347:19)
    at async executeFlow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:365:31)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:799:28)
    at async Object.buildChatflow (/usr/local/lib/node_modules/flowise/dist/services/predictions/index.js:9:28)
    at async createPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/predictions/index.js:72:41)
2025-08-04 14:28:21 [ERROR]: [server]: Error: Error buildAgentGraph - langChainTracer.convertToRunTree is not a function
Error: Error buildAgentGraph - langChainTracer.convertToRunTree is not a function
    at buildAgentGraph (/usr/local/lib/node_modules/flowise/dist/utils/buildAgentGraph.js:353:15)
    at async executeFlow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:365:31)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:799:28)
    at async Object.buildChatflow (/usr/local/lib/node_modules/flowise/dist/services/predictions/index.js:9:28)
    at async createPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/predictions/index.js:72:41)

**Comment by sbaudet85** [comment]
I just figured out what was wrong!
In my docker-compose.yml, I used to set "LANGCHAIN_TRACING_V2=true".
When setting "LANGCHAIN_TRACING_V2=false", the error disappeared!

**Comment by howardtokka** [comment]
Hi , I have some Agent Flow V1 in 3.0.4, Execute flow within the Agent Flow v1 does not work too.

<img width="684" height="685" alt="Image" src="https://github.com/user-attachments/assets/acfd4574-0d1b-428e-98fc-e67f8d3c7f35" />

<img width="391" height="169" alt="Image" src="https://github.com/user-attachments/assets/f6c2d67b-4cd9-4a18-9fba-ceedc3afe6bb" />

It works after i remove and connect all the conditions from the node.

But it seems the flow cannot be executed.

It just stops at the Execute Flow node

<img width="391" height="405" alt="Image" src="https://github.com/user-attachments/assets/f0e5bc73-64fa-4927-8a39-7bca5a842ccf" />

**Comment by takefy-dev** [comment]
@HenryHengZJ please we are a huge company using this. Please how can we pay for priority support or something ?

**Comment by antawiryawan** [comment]
Hi everyone,

I got the same issue after updated it from 3.0.1 to 3.0.4. I tried duplicating the flow and saving it with another name, which solved the problem. Maybe you can try it too.
