### ISSUE TITLE
[BUG] MODULE_NOT_FOUND : node_modules/openai/helpers/zod.js === since updating to 2.0.5

### ISSUE THREAD

**Issue by Sarahkunk** [FlowiseAI/Flowise#3067]
**Describe the bug**
Error on build time and run time : 

[MODULE_NOT_FOUND] ModuleLoadError Plugin: flowise: [MODULE_NOT_FOUND] require failed to load <project-path>/packages/server/dist/commands/start.js Cannot find module <project-path>/node_modules/.pnpm/@langchain+openai@0.2.7_encoding@0.1.13_langchain@0.2.17_4oakmayaajwtwwxwds3rutg7xa_/node_modules/openai/helpers/zod.js

module: @oclif/core@1.26.2
task: toCached
plugin: flowise
root: <project-path>/packages/server

More specifically I think this occurred after the commit number d5153c384076d889ed6b70a0d1db6b51a2d472b2 but I haven't rolled back commits yet to pinpoint the exact commit. Any help would be really appreciated, thanksss

**Comment by HenryHengZJ** [comment]
is a clean install and fresh build works? 
```
pnpm i
pnpm clean
pnpm build-force
```

**Comment by sagar-jani** [comment]
I am getting the same error with pnpm and docker both.
